resources:
  - orders.yaml

configMapGenerator:
  - name: orders-env
    envs:
      - orders.base.env

secretGenerator: []

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: orders
