apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: orders-aws-secrets
spec:
  provider: aws

  parameters:
    region: us-east-1

    objects: |
      - objectName: "orders/postgres-credentials"
        objectType: "secretsmanager"
        jmesPath:
          - path: POSTGRES_USER
            objectAlias: POSTGRES_USER
          - path: POSTGRES_PASSWORD
            objectAlias: POSTGRES_PASSWORD
          - path: POSTGRES_DB
            objectAlias: POSTGRES_DB

  secretObjects:
    - secretName: postgres-credentials
      type: Opaque
      data:
        - objectName: POSTGRES_USER
          key: POSTGRES_USER
        - objectName: POSTGRES_PASSWORD
          key: POSTGRES_PASSWORD
        - objectName: POSTGRES_DB
          key: POSTGRES_DB